n1=int(input("Enter the first number:"))
n2=int(input("Enter the second number:"))
print("Addition:",(n1+n2))
print("Substraction:",(n1-n2))
print("Multiplication:",(float(n1*n2)))
print("Division:",(float(n1/n2)))
